### ISSUE TITLE
Add common code

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/logging_bugfender#5]
Add common code to this package that appears in almost every project, but in a slightly different form. See below.

Let's make it consistent.

```dart
Future<void> _setupLogger(AppConfig config) async {
  if (config.debugMode) {
    Logger.root.level = Level.ALL;
    Logger.root.onRecord.listen((record) {
      final firstLine = StringBuffer()
        ..writeAll(
          <String>[
            record.level.name,
            if (record.loggerName.isNotEmpty) record.loggerName,
            record.message,
          ],
          ': ',
        );

      debugPrint(firstLine.toString());
      if (record.error != null) {
        debugPrint(record.error.toString());
      }
      if (record.stackTrace != null) {
        debugPrint(record.stackTrace.toString());
      }
    });
  } else {
    Logger.root.level = Level.INFO;
    LoggingBugfenderListener(config.bugfenderKey).listen(Logger.root);
  }

  final flutterErrorLogger = Logger('FlutterError');
  FlutterError.onError = (details) {
    if (config.debugMode) {
      FlutterError.dumpErrorToConsole(details);
    } else {
      flutterErrorLogger.warning(
        details.summary.name,
        details.exception,
        details.stack,
      );
    }
  };
}
```

**Comment by Albert221** [comment]
We could provide few `Printer` classes, for production and development purposes.

I'd love to see colored output on dev ❤️

**Comment by bartekpacia** [comment]
Some code that might be useful from `package:logger`:
- https://github.com/leisim/logger/blob/master/lib/src/ansi_color.dart
- https://github.com/leisim/logger/blob/master/lib/src/printers/simple_printer.dart

**Comment by bartekpacia** [comment]
TBH I'm not sure whether additional Loggers/Printers should be included in this project/package. Its purpose is to integrate `package:logging` and `flutter_bugfender`, not to provide some custom colorful logging. It's a cool idea but maybe we should think of adding it in a separate package? Something like a reincarnation of [`package:leancode_logging_flutter`](https://pub.dev/packages/leancode_logging_flutter).

btw @Albert221, what do you exactly mean by "`Printer` class"? Such a thing exists neither in `package:logging` nor `package:flutter_bugfender`.

**Comment by Albert221** [comment]
I don't agree we need to keep that package really that atomic. I'd like to keep this package as a toolkit of a kind, that helps integrate the `logger` with Bugfender in a Flutter environment. Providing additional, optional functionality that could reduce repeated code among the projects that use it, such as formatting the `LogRecord` to a string with every piece of information needed is one of such cases.

---

By printers, I meant the formatters themselves, so that, e.g. when we read logs on a development machine we could have all the fancy colors and when sending logs to the server it would be kept plain text.

Currently, we have `printToConsole` parameter of the `LoggingBugfenderListener`, which is just passed to the Bugfender plugin. We can alter it so that Bugfender never prints to the console itself, but we do. And we could let the developer choose the strategy of the formatting (the formatter itself) for the console printing. It could be:
* `consoleStrategy: const NeverPrintStrategy()`
* `consoleStrategy: const PlainTextPrintStrategy()`
* `consoleStrategy: const ColoredTextPrintStrategy()`
